### ISSUE TITLE
sent_id referenced before assignment

### ISSUE THREAD

**Issue by benradford** [openeventdata/petrarch#96]
I'm opening an issue for the following error:

```python
Traceback (most recent call last):
  File "/Users/Ben/github/petrarch/petrarch/petrarch.py", line 2905, in <module>
    main()
  File "/Users/Ben/github/petrarch/petrarch/petrarch.py", line 2798, in main
    run(paths, cli_args.output, cli_args.parsed)
  File "/Users/Ben/github/petrarch/petrarch/petrarch.py", line 2861, in run
    events = PETRreader.read_xml_input(filepaths, s_parsed)
  File "/Users/Ben/Github/petrarch/petrarch/PETRreader.py", line 1888, in read_xml_input
    holding[entry_id]['sents'][sent_id] = sent_dict
UnboundLocalError: local variable 'sent_id' referenced before assignment
```
I'm making a system call to petrarch.py from within R (hence the R traceback). Petrarch will code subsets of my file, but not the entire thing. I'll take a look inside Petrarch and try to figure it out, but if you guys have any ideas that'd be great too.

**Comment by johnb30** [comment]
Which PETRARCH version are you using?

**Comment by benradford** [comment]
Petrarch 1. I cloned the repo about a month ago, so it should be up to date.

**Comment by johnb30** [comment]
Did you ever get this fixed?

**Comment by benradford** [comment]
I can't replicate it after switching to terminal (as opposed to piping system commands from R) so I haven't bothered to dig any deeper. Could have been a parsing issue. I'm going to close it until further notice.
