### ISSUE TITLE
Are their benchmark datasets on which Petrarch's precision and recall are evaluated?

### ISSUE THREAD

**Issue by riedelcastro** [openeventdata/petrarch#97]
I am really curious about the accuracy (precision & recall) of Petrarch. I am sure there must be a paper that mentions this, but haven't been able to find it. 

Thanks for a great source, btw!

**Comment by johnb30** [comment]
There aren't any metrics currently. The major hangup is the lack of an existing set of "gold standard" cases against which to measure performance. There are a few different efforts to generate such cases, however.

**Comment by riedelcastro** [comment]
Thanks! Could you point me to these efforts?

**Comment by johnb30** [comment]
None of them are public, currently (one is part of my dissertation work...). The only thing close to a public evaluation of political event extractors in the vein of PETRARCH that I know of is http://brenocon.com/Boschee2013Events.pdf.

**Comment by riedelcastro** [comment]
Thanks!
